version: 2.1

jobs:
  build-and-test:
    macos:
      xcode: "14.3"
    steps:
      - checkout
      - run: xcodebuild clean build test -project EssentialFeed.xcodeproj -scheme "CI" CODE_SIGNING_IDENTITY="" CODE_SIGNING_REQUIRED=NO

workflows:
  build_and_test:
    jobs:
      - build_and_test
