version: 2.1

orbs:
  xcode: circleci/macos@2.3.4

jobs:
  build-and-test:
    macos:
      xcode: "14.3.0"
    steps:
      - checkout
      - run:
          name: "Build and Test Project"
          command: |
            set -o pipefail && xcodebuild \
              clean \
              build \
              test \
              -project "EssentialFeed.xcodeproj" \
              -scheme "CI" \
              CODE_SIGNING_IDENTITY="" \
              CODE_SIGNING_REQUIRED=NO \
              | xcpretty -c
      - store_artifacts:
          path: "build/reports"
          destination: "reports"

workflows:
  build-and-test:
    jobs:
      - build-and-test
